import { Map, List } from 'immutable';
import { initialState } from './';

export const mockedRequestState = initialState.merge(Map({ isFetchingVendors: true }));

export const mockedVendors = [
  {
    id: 4,
    primary: true,
    type: 'beneficial_owner',
    present_at_home_visit: true,
    title: 'Mr',
    first_names: 'Jessie',
    last_name: 'Wongus',
    email_address: 'simon@gmail.com',
    phone_number: '07000000000',
    date_of_birth: '1984-04-23',
    occupation: 'Manager',
    politically_exposed: true,
    living_at_the_property_you_are_selling: false,
    living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
    country_of_residence: 'France',
    addresses: [
      {
        id: 1,
        sub_building: null,
        building_name: null,
        building_number: '44',
        street: 'Evelyn Field',
        town: 'Holmesborough',
        county: 'Suffolk',
        postcode: 'L38 9EB',
        position: 0,
      },
      {
        id: 2,
        sub_building: null,
        building_name: null,
        building_number: '892',
        street: 'Alexander Junctions',
        town: 'Graceview',
        county: 'Suffolk',
        postcode: 'WF9 2JY',
        position: 1,
      },
    ],
    owned_since_month: null,
    owned_since_year: null,
    reason_for_selling: 'I need a bigger house',
  },
  {
    id: 35,
    primary: false,
    type: 'beneficial_owner',
    present_at_home_visit: true,
    title: 'Mr',
    first_names: 'Luke',
    last_name: 'Pearl',
    email_address: null,
    phone_number: null,
    date_of_birth: null,
    occupation: null,
    politically_exposed: null,
    living_at_the_property_you_are_selling: null,
    living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
    country_of_residence: null,
    addresses: [],
    owned_since_month: null,
    owned_since_year: null,
    reason_for_selling: null,
  },
];

export const mockedState = Map({
  isFetchingVendors: false,
  vendors: List([
    {
      id: 4,
      primary: true,
      type: 'beneficial_owner',
      present_at_home_visit: true,
      title: 'Mr',
      first_names: 'Jessie',
      last_name: 'Wongus',
      email_address: 'simon@gmail.com',
      phone_number: '07000000000',
      date_of_birth: '1984-04-23',
      occupation: 'Manager',
      politically_exposed: true,
      living_at_the_property_you_are_selling: false,
      living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
      country_of_residence: 'France',
      addresses: [
        {
          id: 1,
          sub_building: null,
          building_name: null,
          building_number: '44',
          street: 'Evelyn Field',
          town: 'Holmesborough',
          county: 'Suffolk',
          postcode: 'L38 9EB',
          position: 0,
        },
        {
          id: 2,
          sub_building: null,
          building_name: null,
          building_number: '892',
          street: 'Alexander Junctions',
          town: 'Graceview',
          county: 'Suffolk',
          postcode: 'WF9 2JY',
          position: 1,
        },
      ],
      owned_since_month: null,
      owned_since_year: null,
      reason_for_selling: 'I need a bigger house',
    },
    {
      id: 35,
      primary: false,
      type: 'beneficial_owner',
      present_at_home_visit: true,
      title: 'Mr',
      first_names: 'Luke',
      last_name: 'Pearl',
      email_address: null,
      phone_number: null,
      date_of_birth: null,
      occupation: null,
      politically_exposed: null,
      living_at_the_property_you_are_selling: null,
      living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
      country_of_residence: null,
      addresses: [],
      owned_since_month: null,
      owned_since_year: null,
      reason_for_selling: null,
    },
  ]),
});

export const mockedStateAfterDelete = Map({
  isFetchingVendors: false,
  vendors: List([
    {
      id: 4,
      primary: true,
      type: 'beneficial_owner',
      present_at_home_visit: true,
      title: 'Mr',
      first_names: 'Jessie',
      last_name: 'Wongus',
      email_address: 'simon@gmail.com',
      phone_number: '07000000000',
      date_of_birth: '1984-04-23',
      occupation: 'Manager',
      politically_exposed: true,
      living_at_the_property_you_are_selling: false,
      living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
      country_of_residence: 'France',
      addresses: [
        {
          id: 1,
          sub_building: null,
          building_name: null,
          building_number: '44',
          street: 'Evelyn Field',
          town: 'Holmesborough',
          county: 'Suffolk',
          postcode: 'L38 9EB',
          position: 0,
        },
        {
          id: 2,
          sub_building: null,
          building_name: null,
          building_number: '892',
          street: 'Alexander Junctions',
          town: 'Graceview',
          county: 'Suffolk',
          postcode: 'WF9 2JY',
          position: 1,
        },
      ],
      owned_since_month: null,
      owned_since_year: null,
      reason_for_selling: 'I need a bigger house',
    },
  ]),
});

export const mockedVendor = {
  id: 55,
  primary: false,
  type: 'beneficial_owner',
  present_at_home_visit: true,
  title: 'Mr',
  first_names: 'Luke',
  last_name: 'Pearl',
  email_address: null,
  phone_number: null,
  date_of_birth: null,
  occupation: null,
  politically_exposed: null,
  living_at_the_property_you_are_selling: null,
  living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
  country_of_residence: null,
  addresses: [],
  owned_since_month: null,
  owned_since_year: null,
  reason_for_selling: null,
};

export const mockedStateAfterAdd = Map({
  isFetchingVendors: false,
  vendors: List([
    {
      id: 4,
      primary: true,
      type: 'beneficial_owner',
      present_at_home_visit: true,
      title: 'Mr',
      first_names: 'Jessie',
      last_name: 'Wongus',
      email_address: 'simon@gmail.com',
      phone_number: '07000000000',
      date_of_birth: '1984-04-23',
      occupation: 'Manager',
      politically_exposed: true,
      living_at_the_property_you_are_selling: false,
      living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
      country_of_residence: 'France',
      addresses: [
        {
          id: 1,
          sub_building: null,
          building_name: null,
          building_number: '44',
          street: 'Evelyn Field',
          town: 'Holmesborough',
          county: 'Suffolk',
          postcode: 'L38 9EB',
          position: 0,
        },
        {
          id: 2,
          sub_building: null,
          building_name: null,
          building_number: '892',
          street: 'Alexander Junctions',
          town: 'Graceview',
          county: 'Suffolk',
          postcode: 'WF9 2JY',
          position: 1,
        },
      ],
      owned_since_month: null,
      owned_since_year: null,
      reason_for_selling: 'I need a bigger house',
    },
    {
      id: 35,
      primary: false,
      type: 'beneficial_owner',
      present_at_home_visit: true,
      title: 'Mr',
      first_names: 'Luke',
      last_name: 'Pearl',
      email_address: null,
      phone_number: null,
      date_of_birth: null,
      occupation: null,
      politically_exposed: null,
      living_at_the_property_you_are_selling: null,
      living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
      country_of_residence: null,
      addresses: [],
      owned_since_month: null,
      owned_since_year: null,
      reason_for_selling: null,
    },
    {
      id: 55,
      primary: false,
      type: 'beneficial_owner',
      present_at_home_visit: true,
      title: 'Mr',
      first_names: 'Luke',
      last_name: 'Pearl',
      email_address: null,
      phone_number: null,
      date_of_birth: null,
      occupation: null,
      politically_exposed: null,
      living_at_the_property_you_are_selling: null,
      living_at_the_property_you_are_selling_for_at_least_twelve_months: null,
      country_of_residence: null,
      addresses: [],
      owned_since_month: null,
      owned_since_year: null,
      reason_for_selling: null,
    },
  ]),
});
